branch-defaults:
  ft_endpoint:
    environment: null
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: image-filtering-microservice
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
